# Generated by Django 3.2 on 2021-05-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao_de_ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.FloatField()),
                ('dia', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'cartoes',
                'db_table': 'cartao',
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sindicato', models.CharField(default='Sindicato Basico', max_length=20)),
                ('taxa', models.FloatField()),
                ('valor_sindicato', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'sindicatos',
                'db_table': 'sindicato',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('valor', models.FloatField()),
                ('percentual_na_venda', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Horista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASSALARIADO', 'Assalariado'), ('HORISTA', 'Horista'), ('COMISSIONADO', 'Comissionado')], default='Assalariado', max_length=12)),
                ('metodo_de_pagamento', models.CharField(choices=[('MAOS', 'Cheque-Maos'), ('CORREIO', 'Cheque-Correio'), ('DEPOSITO', 'Deposito')], default='Cheque-Maos', max_length=8)),
                ('salario', models.FloatField()),
                ('valor_hora', models.FloatField()),
                ('cartao_de_ponto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empregado.cartao_de_ponto')),
                ('sindicato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empregado.sindicato')),
            ],
            options={
                'verbose_name_plural': 'horistas',
                'db_table': 'horista',
            },
        ),
        migrations.CreateModel(
            name='Comissionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASSALARIADO', 'Assalariado'), ('HORISTA', 'Horista'), ('COMISSIONADO', 'Comissionado')], default='Assalariado', max_length=12)),
                ('metodo_de_pagamento', models.CharField(choices=[('MAOS', 'Cheque-Maos'), ('CORREIO', 'Cheque-Correio'), ('DEPOSITO', 'Deposito')], default='Cheque-Maos', max_length=8)),
                ('salario', models.FloatField()),
                ('sindicato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empregado.sindicato')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empregado.venda')),
            ],
            options={
                'verbose_name_plural': 'comissionados',
                'db_table': 'comissionado',
            },
        ),
        migrations.CreateModel(
            name='Assalariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ASSALARIADO', 'Assalariado'), ('HORISTA', 'Horista'), ('COMISSIONADO', 'Comissionado')], default='Assalariado', max_length=12)),
                ('metodo_de_pagamento', models.CharField(choices=[('MAOS', 'Cheque-Maos'), ('CORREIO', 'Cheque-Correio'), ('DEPOSITO', 'Deposito')], default='Cheque-Maos', max_length=8)),
                ('salario', models.FloatField()),
                ('dia_do_pagamento', models.DateField()),
                ('sindicato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empregado.sindicato')),
            ],
            options={
                'verbose_name_plural': 'assalariados',
                'db_table': 'assalariado',
            },
        ),
    ]
